.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FEATURE" "1" "November 2019" "iFixit" ""
.
.SH "NAME"
\fBfeature\fR \- Perform actions on a git feature branch\.
.
.SH "SYNOPSIS"
\fBfeature\fR \fIcommand\fR [\fIargs\fR]
.
.SH "DESCRIPTION"
\fBFeature\fR is a helper script for a modified git\-flow model\.
.
.SH "COMMANDS"
.
.TP
feature\-list(1)
List the current branch and any available feature branches\.
.
.TP
feature\-start(1)
Start a new feature branch\.
.
.TP
feature\-url(1)
Get the url of a branch\'s pull request\.
.
.TP
feature\-switch(1)
Switch to another feature branch\.
.
.TP
feature\-finish(1)
Finish this feature branch (push and open a pull request)\.
.
.TP
feature\-finish\-issue(1)
Finish this feature branch and attach it to an issue\.
.
.TP
feature\-merge(1)
Merge a feature branch into the development branch\.
.
.TP
feature\-pull(1)
Pull remote updates into this branch\.
.
.TP
feature\-prune(1)
Remove old branches on local or origin\.
.
.TP
feature\-status(1)
Determine if the current branch is up\-to\-date with the remote branch\.
.
.TP
feature\-stashes(1)
Show stashes saved on the current branch\.
.
.TP
feature\-github\-test(1)
Test Github authentication\.
.
.SH "COPYRIGHT"
Copyright (c) 2012\-2013 iFixit\.
.
.SH "SEE ALSO"
git(1)
.
.SH "WWW"
https://github\.com/iFixit/git\-scripts
