.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HOTFIX\-MERGE" "1" "April 2013" "iFixit" ""
.
.SH "NAME"
\fBhotfix\-merge\fR \- Merge a hotfix branch into stable and the development branch\.
.
.SH "SYNOPSIS"
\fBhotfix merge\fR [name\-of\-hotfix]
.
.SH "DESCRIPTION"
Merge a hotfix branch into stable and \fIfeature\.development_branch\fR\. If \fBname\-of\-hotfix\fR is not specified, the current branch will be used\. \fBhotfix merge\fR will attempt to prefill the merge message with a link to and the text of the pull request associated with the branch\.
.
.P
Deletes the local copy of the branch on success\.
.
.SH "COPYRIGHT"
Copyright (c) 2012\-2013 iFixit\.
.
.SH "SEE ALSO"
hotfix(1), feature\-merge(1)
.
.SH "WWW"
https://github\.com/iFixit/git\-scripts
